
server:

  port: 8999



spring:

  datasource:

    name: jur

    type: com.alibaba.druid.pool.DruidDataSource



    druid:

      driver-class-name: com.mysql.jdbc.Driver



      url: jdbc:mysql://127.0.0.1:3306/gym

      username: root

      password: 123456



      initial-size: 1

      min-idle: 1

      max-active: 20



      max-wait: 60000



      time-between-eviction-runs-millis: 60000



      min-evictable-idle-time-millis: 300000

      validation-query: SELECT 'x'

      test-while-idle: true

      test-on-borrow: false

      test-on-return: false



      pool-prepared-statements: false

      max-pool-prepared-statement-per-connection-size: 20



      filters: stat,wall

      stat-view-servlet:

        enabled: true

        url-pattern: /druid/*

  main:

    allow-bean-definition-overriding: true





mybatis:

  mapper-locations: classpath:mapper/*Mapper.xml

logging:

  level:

    com.zhiyou100.druid.mapper : debug
    #----------------------------------------------
qiniu:
  #  七牛云账号对应的  AccessKey
  accessKey: SKaGwe4HkYyakAENL6zxQINkg7J1TPYDlCl17JR3
  #  七牛云账号对应的  SecretKey
  secretKey: 8L5aYhki1rWZUagzR4Ym7LP2Az7K5q9liHRBlw_G
  #  存储空间名字
  bucket: qiniu-springboot
  #   图片上传成功后的返回地址,我们图片一般上传完之后需要回显
  path: qiniu-springboot.s3-cn-east-1.qiniucs.com
