server:
  port: 8000
spring:
  application:
    name: server-weather-city
  # 配置数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gym?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 123456
  # 配置Redis
  redis:
    host: 192.168.179.128
    port: 6379
    #没有密码就空着，默认没有密码
    password:
    #以下配置可写可不写
    #连接超时时间（2.0中该参数的类型为Duration，这里在配置的时候需要指明单位
    timeout: 2000ms
    #连接池最大连接数（使用负值表示没有限制)
    max-active: 8
    #连接池最大阻塞等待时间（使用负值表示没有限制）
    max-wait: -1ms
    #连接池中的最大空闲连接
    max-idle: 8
    #连接池中的最小空闲连接
    min-idle: 0


qiniu:

  accessKey: SKaGwe4HkYyakAENL6zxQINkg7J1TPYDlCl17JR3

  secretKey: 8L5aYhki1rWZUagzR4Ym7LP2Az7K5q9liHRBlw_G

  bucket: qiniu-springboot

  path: qiniu-springboot.s3-cn-east-1.qiniucs.com