
server:

  port: 8999



spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html

  datasource:

    name: jur

    type: com.alibaba.druid.pool.DruidDataSource



    druid:

      driver-class-name: com.mysql.jdbc.Driver



      url: jdbc:mysql://127.0.0.1:3306/gym

      username: root

      password: 123456



      initial-size: 1

      min-idle: 1

      max-active: 20



      max-wait: 60000



      time-between-eviction-runs-millis: 60000



      min-evictable-idle-time-millis: 300000

      validation-query: SELECT 'x'

      test-while-idle: true

      test-on-borrow: false

      test-on-return: false



      pool-prepared-statements: false

      max-pool-prepared-statement-per-connection-size: 20



      filters: stat,wall

      stat-view-servlet:

        enabled: true

        url-pattern: /druid/*

  main:

    allow-bean-definition-overriding: true





mybatis:

  mapper-locations: classpath:mapper/*Mapper.xml

logging:

  level:

    com.zhiyou100.druid.mapper : debug



    #----------------------------------------------
qiniu:

  accessKey: SKaGwe4HkYyakAENL6zxQINkg7J1TPYDlCl17JR3

  secretKey: 8L5aYhki1rWZUagzR4Ym7LP2Az7K5q9liHRBlw_G

  bucket: qiniu-springboot

  path: qiniu-springboot.s3-cn-east-1.qiniucs.com



redis:
    host: 192.168.197.128
    port: 6379

    password:

    timeout: 2000ms

    max-active: 8

    max-wait: -1ms

    max-idle: 8

    min-idle: 0